spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: flash-config-client
eureka:
  client:
    service_url: http://eureka-dev.com:7001/eureka/
      
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: flash-config-client
eureka:
  client:
    service_url: http://eureka-test.com:7001/eureka/